@MontrealFoodViolations.Api_HostAddress = http://localhost:5067

### Liste paginée
GET {{MontrealFoodViolations.Api_HostAddress}}/api/violations?page=1&pageSize=10
Accept: application/json

### Recherche
GET {{MontrealFoodViolations.Api_HostAddress}}/api/violations/search?search=pizza&page=1&pageSize=25
Accept: application/json

### Statistiques
GET {{MontrealFoodViolations.Api_HostAddress}}/api/violations/stats
Accept: application/json

### Fiche établissement
GET {{MontrealFoodViolations.Api_HostAddress}}/api/violations/business/760
Accept: application/json

### Sync manuelle
POST {{MontrealFoodViolations.Api_HostAddress}}/api/sync
Accept: application/json

### Statut sync
GET {{MontrealFoodViolations.Api_HostAddress}}/api/sync/status
Accept: application/json
