// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MontrealFoodViolations.Infrastructure.Data;

#nullable disable

namespace MontrealFoodViolations.Infrastructure.Migrations
{
    [DbContext(typeof(MontrealFoodViolationsDbContext))]
    [Migration("20260830041957_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("MontrealFoodViolations.Domain.Entities.DatasetSyncState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DatasetName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastETag")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastHash")
                        .HasColumnType("TEXT");

                    b.Property<int>("LastInsertedRows")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastModified")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LastRowCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LastSkippedRows")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastSuccessAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastSyncCompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastSyncStartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("LastUnchangedRows")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LastUpdatedRows")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DatasetName")
                        .IsUnique();

                    b.ToTable("DatasetSyncStates");
                });

            modelBuilder.Entity("MontrealFoodViolations.Domain.Entities.Violation", b =>
                {
                    b.Property<long>("IdPoursuite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adresse")
                        .HasColumnType("TEXT");

                    b.Property<long?>("BusinessId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Categorie")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("DateJugement")
                        .HasColumnType("TEXT");

                    b.Property<string>("DateStatut")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Etablissement")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Montant")
                        .HasColumnType("TEXT");

                    b.Property<string>("Proprietaire")
                        .HasColumnType("TEXT");

                    b.Property<string>("Statut")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ville")
                        .HasColumnType("TEXT");

                    b.HasKey("IdPoursuite");

                    b.HasIndex("BusinessId");

                    b.HasIndex("Categorie");

                    b.HasIndex("Date");

                    b.HasIndex("Etablissement");

                    b.HasIndex("Statut");

                    b.HasIndex("Ville");

                    b.ToTable("Violations");
                });
#pragma warning restore 612, 618
        }
    }
}
